export const additiveInfo: Record<string, { description: string; risk: 'low' | 'medium' | 'high' | 'unknown' }> = {
  e100: { description: "Curcumină – colorant natural galben extras din turmeric.", risk: "low" },
  e101: { description: "Riboflavină – colorant galben natural, vitamina B2.", risk: "low" },
  e110: { description: "Sunset Yellow – colorant artificial, poate cauza reacții alergice.", risk: "medium" },
  e120: { description: "Carmin – colorant roșu natural obținut din insecte coșenile.", risk: "medium" },
  e150d: { description: "Caramel IV – colorant maro folosit în băuturi carbogazoase.", risk: "medium" },
  e200: { description: "Acid sorbic – conservant folosit împotriva mucegaiului.", risk: "low" },
  e202: { description: "Sorbat de potasiu – conservant folosit în produse lactate și sucuri.", risk: "medium" },
  e211: { description: "Benzoat de sodiu – conservant controversat, asociat cu hiperactivitate.", risk: "high" },
  e220: { description: "Dioxid de sulf – conservant folosit în vinuri și fructe uscate.", risk: "high" },
  e250: { description: "Nitrit de sodiu – conservant în carne procesată, asociat cu riscuri cancerigene.", risk: "high" },
  e260: { description: "Acid acetic – oțet alimentar, folosit ca regulator de aciditate.", risk: "low" },
  e300: { description: "Acid ascorbic – vitamina C, antioxidant natural.", risk: "low" },
  e322: { description: "Lecitină – emulgator natural din soia sau gălbenuș de ou.", risk: "low" },
  e330: { description: "Acid citric – acid natural prezent în citrice, folosit ca acidifiant.", risk: "low" },
  e421: { description: "Maltitol – îndulcitor folosit în produse pentru diabetici.", risk: "medium" },
  e460: { description: "Celuloză – agent de îngroșare și stabilizator natural.", risk: "low" },
  e621: { description: "Glutamat monosodic – potențiator de aromă, asociat cu reacții adverse.", risk: "high" },
  e951: { description: "Aspartam – îndulcitor artificial, controversat privind efectele asupra sănătății.", risk: "high" },
  e952: { description: "Acid ciclamic – îndulcitor artificial, interzis în unele țări.", risk: "high" },
  e950: { description: "Acesulfam K – îndulcitor artificial folosit în băuturi light.", risk: "medium" },
};
